version: '3.9'
services:
  web:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: example
    hostname: 'pg'
    container_name: 'pg'
    ports:
      - '5432:5432'
