version: '3.9'

services:
  web:
    build: .
    image: 'exchange'
    environment:
      - DB_CONNECTION_STR=postgresql://postgres:postgres@pg:5432/postgres
      - RABBIT_CONNECTION_STR=pyamqp://admin:mypass@rabbitmq//
    ports:
      - '5000:5000'
    command: python3 app.py
  db:
    image: 'postgres'
    hostname: 'pg'
    container_name: 'pg'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
  celery_worker:
    build: .
    command: celery -A celery_worker worker --loglevel=INFO  --pool=solo
    environment:
      - DB_CONNECTION_STR=postgresql://postgres:postgres@pg:5432/postgres
      - RABBIT_CONNECTION_STR=pyamqp://admin:mypass@rabbitmq//
      - C_FORCE_USER=true






